// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArt7z3Cl-YmWlwfn-gnIRqOSiFXRpfSV4',
    appId: '1:361955188087:web:65ab891a0759e23d8e5572',
    messagingSenderId: '361955188087',
    projectId: 'up-run-7f05d',
    authDomain: 'up-run-7f05d.firebaseapp.com',
    databaseURL: 'https://up-run-7f05d-default-rtdb.firebaseio.com',
    storageBucket: 'up-run-7f05d.appspot.com',
    measurementId: 'G-W9CG7J0PRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14RdwUd9jhetxmcpHDXtffHvEVeSONJQ',
    appId: '1:361955188087:android:b8d11436c98c93bf8e5572',
    messagingSenderId: '361955188087',
    projectId: 'up-run-7f05d',
    databaseURL: 'https://up-run-7f05d-default-rtdb.firebaseio.com',
    storageBucket: 'up-run-7f05d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZFdu6pIBbDqMeqluBs1f9BcxbblXtc70',
    appId: '1:361955188087:ios:c9465bcfba06d68f8e5572',
    messagingSenderId: '361955188087',
    projectId: 'up-run-7f05d',
    databaseURL: 'https://up-run-7f05d-default-rtdb.firebaseio.com',
    storageBucket: 'up-run-7f05d.appspot.com',
    iosClientId: '361955188087-dmb40stelctc1fs2ubv74clk44ln9nom.apps.googleusercontent.com',
    iosBundleId: 'com.toprograms.up.run',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZFdu6pIBbDqMeqluBs1f9BcxbblXtc70',
    appId: '1:361955188087:ios:d6ada3dc08fe1e368e5572',
    messagingSenderId: '361955188087',
    projectId: 'up-run-7f05d',
    databaseURL: 'https://up-run-7f05d-default-rtdb.firebaseio.com',
    storageBucket: 'up-run-7f05d.appspot.com',
    iosClientId: '361955188087-vd9mrqp0cftt8qc6sp61j3t2edqad8or.apps.googleusercontent.com',
    iosBundleId: 'com.example.runapp.runApp',
  );
}
